id: I839F8374
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T20:01:59+00:00'
last_modified: '2022-06-08T02:10:35.316571+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS44054
  title: གསེར་ཐལ་གྱི་ལོ་རྒྱུས་དང་སྲོལ་རྒྱུན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    5FB4:
      image_group_id: I1GS49714
      title: ''
      total_pages: 121
      order: 1
      base_file: 5FB4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
